/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.bsuedu.cad.lab;

import org.springframework.context.annotation.AnnotationConfigApplicationContext;

public class Lab1 {
    public static void main(String[] args) {
        AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext();
        context.scan("ru.bsuedu.cad.lab");
        context.refresh();

        Renderer renderer = context.getBean(DataBaseRenderer.class);
        renderer.render();

        CategoryRequest categoryRequest = context.getBean(CategoryRequest.class);
        categoryRequest.getCategoriesWithMoreThanOneProduct();
    }
}
