/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.bsuedu.cad.lab;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;
import ru.bsuedu.cad.lab.app.Client;

@SpringBootApplication
public class App {

    public static void main(String[] args) throws InterruptedException {
        ApplicationContext applicationContext = SpringApplication.run(App.class, args);
        Client client = applicationContext.getBean(Client.class);
        client.createSampleOrder();

        Thread.sleep(Long.MAX_VALUE);
    }
}
